apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: sshakndr/sampleapp
  newName: sshakndr/sampleapp
  newTag: 6e702f3721caedd253dbb723f94c2764574370dc

resources:
- deployment.yml
- service.yml
- postgres-deployment.yml
- postgres-service.yml
- secret.yml
