apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: sshakndr/sampleapp
  newName: sshakndr/sampleapp
  newTag: 591af39dc9f48eab17ee4ed44e09e499a85397c1

resources:
- deployment.yml
- service.yml
- postgres-deployment.yml
- postgres-service.yml
- secret.yml
