apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: sshakndr/sampleapp
  newName: sshakndr/sampleapp
  newTag: 042553221dbe72c8a6bf9350007851d43cb320a6

resources:
- deployment.yml
- service.yml
- postgres-deployment.yml
- postgres-service.yml
- secret.yml
