apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kondratev-certificate
spec:
  dnsNames:
  - 'kondratev.dacdevops.ru'
  issuerRef:
    kind: ClusterIssuer
    name: yc-clusterissuer
  secretName: kondratev-cert