apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sshakndr-namespace
images:
- name: sshakndr/sampleapp
  newName: sshakndr/sampleapp
  newTag: 6e702f3721caedd253dbb723f94c2764574370dc
- name: nginx
  newName: nginx
  newTag: 1.23.2-alpine

resources:
- ../../base
- namespace.yml
- ingress.yml
- certificate.yml
