apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sshakndr-namespace
images:
- name: nginx
  newName: nginx
  newTag: 1.23.2-alpine
- name: sshakndr/sampleapp
  newName: sshakndr/sampleapp
  newTag: 042553221dbe72c8a6bf9350007851d43cb320a6

resources:
- ../../base
- namespace.yml
- ingress.yml
- certificate.yml
