name: CI workflow
on:
  push: {}
  workflow_dispatch:
    inputs:
      tag:
        default: latest
        description: image tag

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/sampleapp
      TAG: "${{ inputs.tag != '' && inputs.tag || github.ref_name }}"
    steps:
      - name: Check out Project
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: ${{ (github.ref_name == 'main') && 'true' || 'false'}}
          tags: ${{ env.IMAGE }}:${{ github.sha }}

      - name: Check images
        run: |
          docker images

      - name: Tests
        run: |
          docker run --rm ${{ env.IMAGE }}:${{ github.sha }} python manage.py test
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "5.0.1"

    - name: Update Kubernetes base resources
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      run: |
        cd kustomize/base
        kustomize edit set image sshakndr/sampleapp=$DOCKER_USERNAME/sampleapp:$GITHUB_SHA
        cat kustomization.yml

    - name: Update Kubernetes overlays resources
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      run: |
        cd kustomize/overlays/common
        kustomize edit set image sshakndr/sampleapp=$DOCKER_USERNAME/sampleapp:$GITHUB_SHA
        cat kustomization.yml

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "rolling image to tag $GITHUB_SHA"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}